# -*- coding: utf-8 -*-
"""leak_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLfeVNUIIbto0biZVS2sRkMcqRKWVsXi
"""

"""
leak_detection.py — Automated Strategic Leak Detector
Analyses metrics and DataFrames for common bot weaknesses.
"""

import pandas as pd
import numpy as np
from dataclasses import dataclass


@dataclass
class Leak:
    category: str
    name: str
    severity: str          # 'HIGH' / 'MEDIUM' / 'LOW'
    description: str
    evidence: str
    recommendation: str


class LeakDetector:
    """
    Detects strategic leaks from pre-computed metrics + DataFrames.
    """

    THRESHOLDS = {
        # Preflop
        'vpip_min': 0.20,
        'vpip_max': 0.75,
        'pfr_min': 0.10,
        'pfr_vpip_gap_max': 0.30,   # VPIP-PFR gap
        'fold_to_raise_max': 0.70,
        # Auction
        'overbid_rate_max': 0.15,
        'close_loss_max': 0.10,
        'auction_win_ev_min': -30,   # avg profit when winning should be positive
        'bid_stack_ratio_max': 0.08,
        # Aggression
        'cbet_min': 0.40,
        'cbet_max': 0.90,
        'triple_barrel_max': 0.35,
        'river_fold_max': 0.55,
        # Passivity
        'river_check_strong_threshold': 0.30,  # checks river often with winning hand
    }

    def __init__(self, metrics: dict, rounds_df: pd.DataFrame,
                 actions_df: pd.DataFrame, bot_name: str):
        self.m = metrics
        self.rounds_df = rounds_df
        self.actions_df = actions_df
        self.bot_name = bot_name
        self.leaks: list[Leak] = []

    def run(self) -> list[Leak]:
        self.leaks = []
        self._check_preflop()
        self._check_auction()
        self._check_aggression()
        self._check_passivity()
        self._check_risk()
        return sorted(self.leaks, key=lambda l: ['HIGH', 'MEDIUM', 'LOW'].index(l.severity))

    # ── Preflop ───────────────────────────────────────────────────────────────

    def _check_preflop(self):
        pf = self.m.get('preflop', {})
        vpip = pf.get('VPIP', 0)
        pfr = pf.get('PFR', 0)
        fold_to_raise = pf.get('fold_to_raise_pct', 0)
        t = self.THRESHOLDS

        if vpip < t['vpip_min']:
            self.leaks.append(Leak(
                'Preflop', 'Too Tight Preflop', 'MEDIUM',
                f'VPIP is {vpip:.1%}, well below optimal range.',
                f'Bot folds too many playable hands preflop.',
                'Widen opening range, especially from SB/BTN. Call more speculative hands.'))

        if vpip > t['vpip_max']:
            self.leaks.append(Leak(
                'Preflop', 'Too Loose Preflop', 'MEDIUM',
                f'VPIP is {vpip:.1%}, entering too many pots.',
                'Bot is voluntarily paying chips with weak hands preflop.',
                'Tighten opening range, especially out of position.'))

        gap = vpip - pfr
        if gap > t['pfr_vpip_gap_max']:
            self.leaks.append(Leak(
                'Preflop', 'Over-Calling Preflop', 'MEDIUM',
                f'VPIP-PFR gap is {gap:.1%} — calling more than raising.',
                'Bot calls frequently but rarely raises, losing initiative.',
                'Convert some preflop calls to raises to gain positional initiative.'))

        if fold_to_raise > t['fold_to_raise_max']:
            self.leaks.append(Leak(
                'Preflop', 'Folding Too Much to Raises', 'HIGH',
                f'Fold-to-raise is {fold_to_raise:.1%}.',
                'Bot is exploitably tight facing preflop aggression.',
                'Defend the BB more aggressively. 3-bet or call wider vs opens.'))

    # ── Auction ───────────────────────────────────────────────────────────────

    def _check_auction(self):
        auc = self.m.get('auction', {})
        t = self.THRESHOLDS

        overbid_rate = auc.get('overbid_rate', 0)
        close_loss = auc.get('close_loss_rate', 0)
        profit_win = auc.get('avg_profit_when_winning_auction', 0)
        bid_stack = auc.get('bid_to_stack_ratio', 0)
        bid_by_strength = auc.get('avg_bid_by_hand_strength', {})

        if overbid_rate > t['overbid_rate_max']:
            self.leaks.append(Leak(
                'Auction', 'Overbidding (Paying Too Much)', 'HIGH',
                f'Overbid rate {overbid_rate:.1%}: bot wins auction by 100+ chips frequently.',
                'Paying far more than necessary for the information edge.',
                'Use Vickrey logic: bid true value of seeing opponent card. '
                'Winning by 1 chip is optimal; winning by 100+ is pure waste.'))

        if close_loss > t['close_loss_max']:
            self.leaks.append(Leak(
                'Auction', 'Frequently Losing by Small Margin', 'MEDIUM',
                f'Close-loss rate {close_loss:.1%}: losing auction by ≤5 chips.',
                'Opponent has calibrated their bids slightly above ours consistently.',
                'Increase bids by small random amount (e.g. 1–10 chips jitter) to win more close auctions.'))

        if profit_win < t['auction_win_ev_min']:
            self.leaks.append(Leak(
                'Auction', 'Negative EV When Winning Auction', 'HIGH',
                f'Avg profit when winning auction: {profit_win:.1f} chips.',
                'Winning the information does not translate to winning the hand.',
                'Investigate whether revealed card is being used properly. '
                'May be over-paying for low-value reveals (e.g. opponent\'s weak card).'))

        if bid_stack > t['bid_stack_ratio_max']:
            self.leaks.append(Leak(
                'Auction', 'Bid-to-Stack Ratio Too High', 'MEDIUM',
                f'Avg bid is {bid_stack:.1%} of starting stack.',
                'Committing too large a portion of stack to auction.',
                'Cap bids at 5-8% of current stack unless holding very strong hands.'))

        weak_bid = bid_by_strength.get('Weak', 0)
        premium_bid = bid_by_strength.get('Premium', 0)
        if weak_bid > 0 and premium_bid > 0 and weak_bid > premium_bid * 0.7:
            self.leaks.append(Leak(
                'Auction', 'Bidding Same Amount Regardless of Strength', 'MEDIUM',
                f'Weak hand avg bid: {weak_bid:.0f}, Premium hand avg bid: {premium_bid:.0f}.',
                'Not scaling auction bids with hand strength.',
                'With premium hands, bid more aggressively for the reveal. '
                'With weak hands, save chips — the information is less actionable.'))

    # ── Aggression ────────────────────────────────────────────────────────────

    def _check_aggression(self):
        flop = self.m.get('flop', {})
        river = self.m.get('river', {})
        t = self.THRESHOLDS

        cbet = flop.get('cbet_pct', 0)
        triple = river.get('triple_barrel_pct', 0)
        river_fold = river.get('river_fold_pct', 0)

        if cbet < t['cbet_min']:
            self.leaks.append(Leak(
                'Aggression', 'Too Low C-bet Frequency', 'MEDIUM',
                f'C-bet rate is {cbet:.1%}.',
                'Failing to apply pressure after raising preflop.',
                'C-bet more on dry boards or when you have range advantage.'))

        if cbet > t['cbet_max']:
            self.leaks.append(Leak(
                'Aggression', 'C-betting Too Frequently', 'LOW',
                f'C-bet rate {cbet:.1%} is very high.',
                'Over-betting flop may be exploitable by check-raise heavy opponents.',
                'Mix in more checks on wet boards or when out of position.'))

        if triple > t['triple_barrel_max']:
            self.leaks.append(Leak(
                'Aggression', 'Triple Barreling Too Often', 'HIGH',
                f'Triple barrel rate {triple:.1%}.',
                'Committing large amounts on 3 streets — likely bluffing too much on river.',
                'Reduce river bet frequency. Check river more with marginal made hands.'))

        if river_fold > t['river_fold_max']:
            self.leaks.append(Leak(
                'Aggression', 'Folding Too Much on River', 'MEDIUM',
                f'River fold rate {river_fold:.1%}.',
                'May be folding too wide when facing river bets.',
                'Widen river calling range. Evaluate pot odds before folding.'))

    # ── Passivity ─────────────────────────────────────────────────────────────

    def _check_passivity(self):
        pf = self.m.get('preflop', {})
        pfr = pf.get('PFR', 0)

        if pfr < 0.15:
            self.leaks.append(Leak(
                'Passivity', 'Very Low PFR (Under-Raising Preflop)', 'MEDIUM',
                f'PFR {pfr:.1%} is very low.',
                'Bot is rarely taking initiative preflop.',
                'Increase preflop raising frequency, especially in position and with strong hands.'))

    # ── Risk ──────────────────────────────────────────────────────────────────

    def _check_risk(self):
        df = self.rounds_df
        if 'bot_payoff' not in df.columns:
            return

        # Large single-round losses
        big_loss_threshold = -500
        big_losses = df[df['bot_payoff'] < big_loss_threshold]
        big_loss_rate = len(big_losses) / max(len(df), 1)

        if big_loss_rate > 0.05:
            self.leaks.append(Leak(
                'Risk', 'High Rate of Large Single-Round Losses', 'HIGH',
                f'{big_loss_rate:.1%} of rounds end with a loss > 500 chips.',
                f'Average big-loss magnitude: {big_losses["bot_payoff"].mean():.0f} chips.',
                'Review hand histories for over-committing with marginal hands. '
                'Improve fold threshold vs large bets on later streets.'))

        # Loss variance
        loss_std = df['bot_payoff'].std()
        if loss_std > 600:
            self.leaks.append(Leak(
                'Risk', 'Very High Variance', 'LOW',
                f'Payoff std dev: {loss_std:.0f} chips.',
                'High variance indicates very swingy play or frequent all-in situations.',
                'Consider more defensive lines with marginal hands to reduce volatility.'))

    # ── Summary ───────────────────────────────────────────────────────────────

    def summary(self) -> str:
        if not self.leaks:
            return "✅ No significant leaks detected!"

        lines = [f"🚨 {len(self.leaks)} leak(s) detected:\n"]
        for leak in self.leaks:
            icon = {'HIGH': '🔴', 'MEDIUM': '🟡', 'LOW': '🟢'}[leak.severity]
            lines.append(f"{icon} [{leak.severity}] {leak.category}: {leak.name}")
            lines.append(f"   → {leak.description}")
            lines.append(f"   💡 {leak.recommendation}")
            lines.append("")
        return '\n'.join(lines)