# -*- coding: utf-8 -*-
"""report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLfeVNUIIbto0biZVS2sRkMcqRKWVsXi
"""

"""
report.py — Report Generator
Produces executive summary reports in text and HTML format.
"""

import pandas as pd
from pathlib import Path
from datetime import datetime


class ReportGenerator:

    def __init__(self, bot_name: str, metrics: dict, leaks: list,
                 rounds_df: pd.DataFrame, output_dir: str = 'output'):
        self.bot_name = bot_name
        self.metrics = metrics
        self.leaks = leaks
        self.rounds_df = rounds_df
        self.out = Path(output_dir)
        self.out.mkdir(parents=True, exist_ok=True)

    # ── Text Summary ─────────────────────────────────────────────────────────

    def text_summary(self) -> str:
        m  = self.metrics
        pf = m.get('preflop', {})
        auc = m.get('auction', {})
        flop = m.get('flop', {})
        turn = m.get('turn', {})
        river = m.get('river', {})

        lines = [
            "=" * 65,
            f"  IIT POKERBOTS — LOG ANALYSIS REPORT",
            f"  Bot: {self.bot_name}",
            f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "=" * 65,
            "",
            "── EXECUTIVE SUMMARY ─────────────────────────────────────────",
            f"  Total Rounds Analysed : {len(self.rounds_df)}",
            f"  Total P&L             : {m.get('total_payoff', 0):+,} chips",
            f"  Avg P&L per Round     : {m.get('avg_payoff_per_round', 0):+.2f} chips",
            f"  Win Rate              : {m.get('win_rate', 0):.1%}",
            "",
            "── PREFLOP ───────────────────────────────────────────────────",
            f"  VPIP                  : {pf.get('VPIP', 0):.1%}",
            f"  PFR                   : {pf.get('PFR', 0):.1%}",
            f"  3-Bet %               : {pf.get('3bet_pct', 0):.1%}",
            f"  Fold-to-Raise %       : {pf.get('fold_to_raise_pct', 0):.1%}",
            f"  Avg Open Size         : {pf.get('avg_open_size', 0):.0f} chips",
            "",
        ]

        # Profit by preflop action
        pf_profit = pf.get('profit_by_pf_action', {})
        if pf_profit:
            lines.append("  Profit by First PF Action:")
            for action, val in pf_profit.items():
                lines.append(f"    {action:<10}: {val:+.1f} chips avg")
        lines.append("")

        lines += [
            "── AUCTION ───────────────────────────────────────────────────",
            f"  Win Rate              : {auc.get('auction_win_rate', 0):.1%}",
            f"  Avg Bid               : {auc.get('avg_bid', 0):.0f} chips",
            f"  Median Bid            : {auc.get('median_bid', 0):.0f} chips",
            f"  Bid Variance          : {auc.get('bid_variance', 0):.0f}",
            f"  Avg Profit (Win)      : {auc.get('avg_profit_when_winning_auction', 0):+.1f}",
            f"  Avg Profit (Lose)     : {auc.get('avg_profit_when_losing_auction', 0):+.1f}",
            f"  Bid/Stack Ratio       : {auc.get('bid_to_stack_ratio', 0):.1%}",
            f"  Overbid Rate          : {auc.get('overbid_rate', 0):.1%}",
            f"  Close-Loss Rate       : {auc.get('close_loss_rate', 0):.1%}",
            "",
        ]

        bid_strength = auc.get('avg_bid_by_hand_strength', {})
        if bid_strength:
            lines.append("  Avg Bid by Hand Strength:")
            for bucket, val in bid_strength.items():
                lines.append(f"    {bucket:<10}: {val:.0f} chips")
        lines.append("")

        lines += [
            "── FLOP ──────────────────────────────────────────────────────",
            f"  C-Bet %               : {flop.get('cbet_pct', 0):.1%}",
            f"  Fold-to-CBet %        : {flop.get('fold_to_cbet_pct', 0):.1%}",
            "",
            "── TURN ──────────────────────────────────────────────────────",
            f"  Double Barrel %       : {turn.get('double_barrel_pct', 0):.1%}",
            f"  Turn Fold %           : {turn.get('turn_fold_pct', 0):.1%}",
            f"  Avg Profit 2-Barrel   : {turn.get('avg_profit_2barrel', 0):+.1f}",
            "",
            "── RIVER ─────────────────────────────────────────────────────",
            f"  Aggression %          : {river.get('river_aggression_pct', 0):.1%}",
            f"  Fold %                : {river.get('river_fold_pct', 0):.1%}",
            f"  Call Success %        : {river.get('river_call_success_pct', 0):.1%}",
            f"  Triple Barrel %       : {river.get('triple_barrel_pct', 0):.1%}",
            "",
            "── PROFIT BY STREET ──────────────────────────────────────────",
        ]
        for street, stats in m.get('profit_by_street', {}).items():
            lines.append(
                f"  {street:<12}: avg={stats['avg_payoff']:+.1f}  total={stats['total_payoff']:+,}  n={stats['rounds']}")
        lines.append("")

        lines += [
            "── OPPONENT BREAKDOWN ────────────────────────────────────────",
        ]
        for opp, stats in m.get('opponent_breakdown', {}).items():
            lines.append(
                f"  {opp:<20}: avg={stats['avg_payoff']:+.1f}  total={stats['total_payoff']:+,}  n={stats['rounds']}")
        lines.append("")

        # Leaks
        lines += [
            "── LEAK SUMMARY ──────────────────────────────────────────────",
        ]
        if not self.leaks:
            lines.append("  ✅ No significant leaks detected.")
        else:
            high   = [l for l in self.leaks if l.severity == 'HIGH']
            medium = [l for l in self.leaks if l.severity == 'MEDIUM']
            low    = [l for l in self.leaks if l.severity == 'LOW']
            for group, icon in [(high, '🔴'), (medium, '🟡'), (low, '🟢')]:
                for leak in group:
                    lines.append(f"  {icon} [{leak.severity}] {leak.category} — {leak.name}")
                    lines.append(f"       {leak.description}")
                    lines.append(f"       💡 {leak.recommendation}")
                    lines.append("")

        lines.append("=" * 65)
        return '\n'.join(lines)

    # ── HTML Report ──────────────────────────────────────────────────────────

    def html_report(self, chart_paths: dict = None) -> str:
        chart_paths = chart_paths or {}
        m  = self.metrics
        pf = m.get('preflop', {})
        auc = m.get('auction', {})
        flop = m.get('flop', {})
        turn = m.get('turn', {})
        river = m.get('river', {})

        def pct(v): return f"{float(v):.1%}" if v is not None else "N/A"
        def num(v, d=1): return f"{float(v):+.{d}f}" if v is not None else "N/A"

        def metric_card(label, value, color='#74b9ff'):
            return f'''
            <div class="card">
                <div class="card-label">{label}</div>
                <div class="card-value" style="color:{color}">{value}</div>
            </div>'''

        def section(title, content):
            return f'<div class="section"><h2>{title}</h2>{content}</div>'

        def chart_img(path, title=''):
            if path and Path(path).exists():
                import base64
                with open(path, 'rb') as f:
                    b64 = base64.b64encode(f.read()).decode()
                return f'<div class="chart"><p class="chart-title">{title}</p><img src="data:image/png;base64,{b64}" /></div>'
            return ''

        leak_html = ''
        if not self.leaks:
            leak_html = '<p style="color:#00b894">✅ No significant leaks detected!</p>'
        else:
            for leak in self.leaks:
                color = {'HIGH': '#e17055', 'MEDIUM': '#fdcb6e', 'LOW': '#00b894'}[leak.severity]
                leak_html += f'''
                <div class="leak" style="border-left:4px solid {color}">
                    <b style="color:{color}">[{leak.severity}] {leak.category} — {leak.name}</b><br>
                    {leak.description}<br>
                    <span style="color:#aaa">💡 {leak.recommendation}</span>
                </div>'''

        charts_html = ''
        for key, title in [
            ('bankroll',           '📈 Cumulative P&L'),
            ('round_pnl',          '📊 Per-Round P&L'),
            ('action_frequency',   '🃏 Action Frequency by Street'),
            ('auction_distribution', '🎯 Auction Bid Distribution'),
            ('auction_ev',         '💰 Auction EV by Outcome'),
            ('bid_vs_strength',    '📉 Bid vs Hand Strength'),
            ('profit_by_street',   '🗺 Profit by Street'),
            ('fold_heatmap',       '🔥 Fold Rate Heatmap'),
            ('opponent_breakdown', '🆚 Opponent Breakdown'),
        ]:
            charts_html += chart_img(chart_paths.get(key, ''), title)

        html = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Pokerbot Analysis — {self.bot_name}</title>
<style>
  body {{ background:#1a1a2e; color:#eee; font-family:'Segoe UI',sans-serif; margin:0; padding:20px; }}
  h1 {{ color:#74b9ff; border-bottom:2px solid #0f3460; padding-bottom:10px; }}
  h2 {{ color:#a29bfe; margin-top:30px; }}
  .section {{ background:#16213e; border-radius:10px; padding:20px; margin-bottom:20px; }}
  .cards {{ display:flex; flex-wrap:wrap; gap:12px; }}
  .card {{ background:#0f3460; border-radius:8px; padding:14px 20px; min-width:130px; text-align:center; }}
  .card-label {{ font-size:12px; color:#aaa; margin-bottom:4px; }}
  .card-value {{ font-size:22px; font-weight:bold; }}
  .leak {{ background:#0f1631; border-radius:6px; padding:12px 16px; margin:10px 0; }}
  .chart {{ margin:20px 0; }}
  .chart img {{ max-width:100%; border-radius:8px; border:1px solid #333; }}
  .chart-title {{ color:#aaa; font-size:13px; margin-bottom:6px; }}
  table {{ width:100%; border-collapse:collapse; margin-top:12px; }}
  th {{ background:#0f3460; color:#74b9ff; padding:8px 12px; text-align:left; }}
  td {{ padding:7px 12px; border-bottom:1px solid #2d3561; }}
  tr:hover td {{ background:#0d2137; }}
</style>
</head>
<body>
<h1>🃏 IIT Pokerbots Log Analysis</h1>
<p style="color:#aaa">Bot: <b style="color:white">{self.bot_name}</b> &nbsp;|&nbsp; Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} &nbsp;|&nbsp; Rounds: {len(self.rounds_df)}</p>

{section("📊 Executive Summary", f'''
<div class="cards">
  {metric_card("Total P&L", f"{m.get('total_payoff',0):+,} chips", "#00b894" if m.get('total_payoff',0) >= 0 else "#e17055")}
  {metric_card("Avg/Round", f"{m.get('avg_payoff_per_round',0):+.1f}", "#00b894" if m.get('avg_payoff_per_round',0) >= 0 else "#e17055")}
  {metric_card("Win Rate", pct(m.get('win_rate',0)), "#74b9ff")}
  {metric_card("Rounds", len(self.rounds_df), "#a29bfe")}
</div>''')}

{section("🃏 Preflop", f'''
<div class="cards">
  {metric_card("VPIP", pct(pf.get('VPIP',0)))}
  {metric_card("PFR", pct(pf.get('PFR',0)))}
  {metric_card("3-Bet %", pct(pf.get('3bet_pct',0)))}
  {metric_card("Fold-to-Raise", pct(pf.get('fold_to_raise_pct',0)))}
  {metric_card("Avg Open", f"{pf.get('avg_open_size',0):.0f} chips")}
</div>''')}

{section("🎯 Auction", f'''
<div class="cards">
  {metric_card("Win Rate", pct(auc.get('auction_win_rate',0)))}
  {metric_card("Avg Bid", f"{auc.get('avg_bid',0):.0f}")}
  {metric_card("Median Bid", f"{auc.get('median_bid',0):.0f}")}
  {metric_card("EV When Win", num(auc.get('avg_profit_when_winning_auction',0)), "#00b894" if (auc.get('avg_profit_when_winning_auction') or 0)>=0 else "#e17055")}
  {metric_card("EV When Lose", num(auc.get('avg_profit_when_losing_auction',0)), "#00b894" if (auc.get('avg_profit_when_losing_auction') or 0)>=0 else "#e17055")}
  {metric_card("Overbid Rate", pct(auc.get('overbid_rate',0)))}
  {metric_card("Close-Loss Rate", pct(auc.get('close_loss_rate',0)))}
</div>''')}

{section("🌊 Post-Flop", f'''
<div class="cards">
  {metric_card("C-Bet %", pct(flop.get('cbet_pct',0)))}
  {metric_card("Fold-to-CBet", pct(flop.get('fold_to_cbet_pct',0)))}
  {metric_card("2x Barrel", pct(turn.get('double_barrel_pct',0)))}
  {metric_card("3x Barrel", pct(river.get('triple_barrel_pct',0)))}
  {metric_card("River Agg", pct(river.get('river_aggression_pct',0)))}
  {metric_card("River Fold", pct(river.get('river_fold_pct',0)))}
  {metric_card("Call Success", pct(river.get('river_call_success_pct',0)))}
</div>''')}

{section("🚨 Detected Leaks", leak_html)}

{section("📈 Charts & Visualizations", charts_html)}

</body>
</html>'''

        path = self.out / f'report_{self.bot_name}.html'
        with open(path, 'w') as f:
            f.write(html)
        return str(path)

    # ── Save Text Report ──────────────────────────────────────────────────────

    def save_text(self) -> str:
        text = self.text_summary()
        path = self.out / f'report_{self.bot_name}.txt'
        with open(path, 'w') as f:
            f.write(text)
        return str(path)